name: 编译兆能M2固件
on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 安装编译依赖
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3

      - name: 更新软件源
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 加载配置文件
        run: make defconfig

      - name: 开始编译
        run: make V=s -j$(nproc) 2>&1 | tee build_log.txt

      - name: 上传编译日志（失败时）
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: 编译日志
          path: build_log.txt

      - name: 上传固件（成功时）
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: 兆能M2固件
          path: bin/targets/**/*
